name: langsplat
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - open-clip-torch
  - pytorch==2.4.0
  - torchvision==0.19.0
  - torchaudio==2.4.0
  - pytorch-cuda=11.8
  - plyfile
  - python
  - pip
  - tqdm
  - opencv
  - tensorboard
  - jaxtyping
  - matplotlib
  - typing
  - pathlib
  - pip:
    - submodules/segment-anything-langsplat
    - submodules/langsplat-rasterization
    - submodules/simple-knn
